### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by heitorpolidoro** [heitorpolidoro/polidoro-config#4]
- [x] heitorpolidoro/polidoro-config#5
- [x] heitorpolidoro/polidoro-config#6
- [x] heitorpolidoro/polidoro-config#8
- [x] heitorpolidoro/polidoro-config#18
